# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Who am I?',               url: 'whoami'}
- {name: 'Computational Scientist', url: 'work'}
- {name: 'Materials Scientist',     url: 'matsci'}
- {name: 'Musician',                url: 'music'}
- {name: 'Self-Publisher',          url: 'go'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'youtube',    link: 'https://www.youtube.com/c/RuoshiSun'}
- {icon: 'music',      link: 'https://imslp.org/wiki/Category:Sun%2C_Ruoshi'}
- {icon: 'amazon',     link: 'https://www.amazon.com/Ruoshi-Sun/e/B01DQ6NH72'}
- {icon: 'envelope',   link: 'mailto:rs7wz@alum.mit.edu'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
